stages:
 - clone
 - build
 - build
 - test
 - deploy
clone:
  stage: clone
  only:
   - push
  variables:
    GIT_URL: https://github.com/example/myproject.git
    CREDENTIAL_ID: null
  script:
   - git clone https://github.com/example/myproject.git
   - git checkout main
build:
  stage: build
  only:
   - push
  script:
   - docker build .
test:
  stage: test
  only:
   - push
  variables:
    TEST_CLASSES: Example.java
  script:
   - mvn test
deploy:
  stage: deploy
  only:
   - push
  script:
   - kubectl apply -f staging-deployment.yaml
