stages:
 - clone
 - build
 - test
 - deploy
clone:
  stage: clone
  only:
   - push
  variables:
    GIT_URL: azedfg
    CREDENTIAL_ID: null
  script:
   - git clone azedfg
   - git checkout kjhgfd
build:
  stage: build
  only:
   - push
  script:
   - hgfd
test:
  stage: test
  only:
   - push
  variables:
    TEST_CLASSES: Example.java
  script:
   - kjhgf
deploy:
  stage: deploy
  only:
   - push
  script:
   - drftgyhuj
